sources:
  - name : raw
    schema : gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description : Has the sales data
      - name: product
        identifier : raw_gz_product
        description : Has the products data
      - name: ship
        identifier : raw_gz_ship
        description : Has the ship data


        