sources:
  - name : raw
    schema : gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description : Has the sales data
      - name: product
        identifier : raw_gz_product
        description : Has the products data
      - name: ship
        identifier : raw_gz_ship
        description : Has the ship data

      - name: adwords
        identifier : raw_gz_adwords
       
      - name: bing
        identifier : raw_gz_bing
        
      - name: criteo
        identifier : raw_gz_criteo

      - name: facebook
        identifier : raw_gz_facebook 